gfortran -c -mcmodel=medium timing.f90
gfortran -c -mcmodel=medium fileFunctions.f90
gfortran -c -mcmodel=medium layerFunctions.f90
gfortran -c -mcmodel=medium matrixFunctions.f90
gfortran -c -mcmodel=medium CNV.f90
gfortran -c -mcmodel=medium MiscFiles\MiscMatrixFunctions.f90
gfortran -c -mcmodel=medium MiscFiles\MiscLayerFunctions.f90
gfortran -c -mcmodel=medium testfunctions.f90
gfortran -mcmodel=medium test.f90 fileFunctions.f90 layerFunctions.o matrixFunctions.o timing.o testfunctions.o MiscMatrixFunctions.o MiscLayerFunctions.o -o test.exe
