gfortran -cpp -c -mcmodel=medium timing.f90
gfortran -cpp -c -mcmodel=medium fileFunctions.f90
gfortran -cpp -c -mcmodel=medium layerFunctions.f90
gfortran -cpp -c -mcmodel=medium matrixFunctions.f90
gfortran -cpp -c -mcmodel=medium CNV.f90
gfortran -cpp -c -mcmodel=medium MiscFiles\MiscMatrixFunctions.f90
gfortran -cpp -c -mcmodel=medium MiscFiles\MiscLayerFunctions.f90
gfortran -cpp -c -mcmodel=medium testingfunctions.f90
gfortran -cpp -c -mcmodel=medium unittests.f90
gfortran -cpp -mcmodel=medium test.f90 fileFunctions.f90 layerFunctions.o matrixFunctions.o timing.o testingfunctions.o unittests.o MiscMatrixFunctions.o MiscLayerFunctions.o -o test.exe
